import Head from "next/head";
import Link from "next/link";

import { plans } from "../utils/consts";

import styles from "../styles/Home.module.scss";

export default function Home() {

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Choose your plan
				</h1>

				<div
					className={styles.rowDiv}
					style={{ marginBlock: "20px" }}
				>
					{
						plans.map(plan => (
							<div key={plan.id} className={styles.planCard}>
								<div className={styles.planCardInfo}>
									<h2>{plan.name}</h2>
									<h3>${plan.price}/mo</h3>
								</div>
								<a 
									className="button" 
									href={`/${plan.id}`}
								>
									Subscribe
								</a>
							</div>
						))
					}
				</div>

				<Link href="/manage">
					<button className="button-outline">
						Manage Subscription
					</button>
				</Link>
			</main>
		</div>
	)
}
